### ISSUE TITLE
ply request

### ISSUE THREAD

**Issue by programlayan** [HazenBabcock/revopoint-python#2]
hello,
Thank you for your great work.
Is it possible to capture a ply file or may be a dph (revopoint default format) file with this useful software.
Thank you.

**Comment by HazenBabcock** [comment]
No, this project doesn't support that. 

I haven't explored it myself, but it looks like Revopoint provides some open source code now.
Some discussion here (towards the end):
https://github.com/frostworx/revopoint-pop2-linux-info/issues/1

The Revopoint repository:
https://github.com/Revopoint/3DViewer

**Comment by programlayan** [comment]
Thank you for your response.
3Dviewer software requires a remote activate for 1 month trial
They request $2000 per device after the trial period
So their "sdk" is crap.
