### ISSUE TITLE
WIFI connection

### ISSUE THREAD

**Issue by ZzhuXia** [HazenBabcock/revopoint-python#4]
Thanks for sharing this. I'm trying to use the package for getting depth frame from Revopoint Mini 2, what's the right way to do so? Should I first have a router and let my PC and revopoint (client mode) all be connected to it. Then using the IP address of the router for accessing the streaming? Appreciate if you can clarify and thanks in advance for your help.

**Comment by HazenBabcock** [comment]
Yes you will need a router with WIFI that the Revopoint can connect to in client mode. Once it is connected you will then need to figure out what IP address the router assigned to the Revopoint. This is not the IP address of the router itself. The IP address may be available somewhere in the Revopoint software? Alternatively, most routers provide a HTTP interface that you can use to see what devices are on the network (though the names are often confusing). You can turn the Revopoint on/off and look for a device appearing/disappearing from the network to determine the Revopoint's IP address.

**Comment by ZzhuXia** [comment]
Thanks for your reply. Tested with your suggestions and the streaming seems fine 👍. Any idea for getting RGB images or further development? May I ask where you adapt these commands?

**Comment by HazenBabcock** [comment]
I was not able to figure out how to get RGB images. My guess is that there is another command that tells the scanner to acquire and return this image, but I was never able to figure out what this command is. It is also possible that these images are sent via a different port (i.e. not HTTP).

You may be able to improve the speed by using compressed images.

I figured out the commands by (1) monitoring the network traffic between the Revopoint software and the scanner using Wireshark and (2) de-compiling the Android app (APK).
